[package]
name = "wess"
version = "1.2.0"
authors = ["Lucas Oliveira olivmath@protonmail.com"]
edition = "2018"

[dependencies]
rocksdb = { version = "0.20.1", features = ["multi-threaded-cf"] }
serde = { version = "1.0.153", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
# tide-testing = "0.1.0"
serde_json = "1.0.94"
lazy_static = "1.4.0"
prometheus = "0.13.3"
wasmtime = "7.0.0"
# quinn = "0.9.3"
sha256 = "1.1.2"
log4rs = "1.2.0"
tide = "0.16.0"
rand = "0.8.5"
log = "0.4.17"
